### ISSUE TITLE
Server updates prevents other users to join the server

### ISSUE THREAD

**Issue by idanest101** [RimworldTogether/Rimworld-Together#123]
When you push new release my friends suddenly cant join the server causing us to switch to the new version and wipe the last run, the prompt logs the following

![image](https://github.com/RimworldTogether/Rimworld-Together/assets/30463593/dd3f3adb-7905-4042-876a-736c7c856707)

is there any thing I can do to keep going with the current run or do I need to wipe the save again?

**Comment by Byte-Nova** [comment]
Hey there, there's additional steps that need to be made if you want to update a server from a previous version instead of starting anew.

Instructions can be found on https://github.com/RimworldTogether/Rimworld-Together/releases/tag/24.6.28.1 patch notes. As an extra thing, make sure both the server and the clients that want to play are updated to latest (24.6.28.1) version
