### ISSUE TITLE
Send Event is not taking in silver in the first trade with an ally

### ISSUE THREAD

**Issue by SfSec** [RimworldTogether/Rimworld-Together#125]
When Sent Event is not taking the silver in the first trade with an ally it is suddenly not possible to Send Events to ally. Any subsequent Send Event --> Popup with Confirm/Cancel --> Confirm click and it does nothing. Confirm stops working.

I will try to copy a instance of my player log as I play and click confirm on the Send Event and then go put a copy of my save into a zip for you to review.
[RimTogether SendEvent Issue.zip](https://github.com/user-attachments/files/16141089/RimTogether.SendEvent.Issue.zip)

I have tried testing restarting the game, talking to the multiplayer host and restarting the server and also adjustments to the sync interval for reference

**Comment by Byte-Nova** [comment]
From looking at the logs, there's something wrong with either the server you are trying to join or your game.

I'd point more towards the second because I'm seeing that the server is sending you information that your game is unable to process (NPC settlements that your game can't place because the factions don't exist, roads that can't be placed because the map you are getting is probably different than it should be, etc.)

While those issues aren't the main one you are having, I'd recommend you try joining with a fresh save to see if it gets fixed.

**Comment by SfSec** [comment]
Hi Byte-Nova, 

I had ended up trying your suggestion last night due to an accident with a colony-wiping event **not related** to the Send-Event stuff I've chatted about.

I did end up starting a new save, and the issues did not fix themselves dramatically. The road errors still exist in the logs, and frankly I do find it odd that sometimes with a new test user I can load a map thats different to the world map that the server has hosted. This is an issue that is reported by multiple players in the multiplayer we play.

These issues are independent of the world map matching the host's world map or not. These issues occur independently of myself as well. There are more users than just me in this multiplayer server that find the same issues with the Send-Event button. We naturally do not understand why some players can load a different world map to others despite loading the same mods in the exact same order as per the rimpy modlist we use.

The multiplayer host decided to reduce the cost of Send-Events to 0 silver to see if they would help send the events since they just werent working after the first test of Send-Event. It turns out if we don't have to submit silver, it will work intermittently to send events.

Naturally, we're not talking about sending events as players are loading in, we're talking about sending events while the players are online together at the same time.

There is no clear timer on when the Send-Event feature is ready again for use. It simply reports "The player you want to send to is currently not available" when I am screen-sharing in a call with other players, I know they're on, and they're available right now.
So far, it seems "Send-Event" is available anywhere between 5-30minutes after a previous Send-Event has been used. The timing is truly variable it seems.

These road errors load into the log if I choose to load the game in singleplayer. The logs are presumably the same even if I loaded into multiplayer because of the client-server architecture used here.

I will load a copy of the logs here in a few hours.

**Comment by Byte-Nova** [comment]
Thanks for the extra feedback on the issue, could you also give us the mod list you guys are using for the server? (enforced and optional, if there's any mod that isn't forced to be used)

Granted from the extra issues you guys are facing (different planet generation and roads failing to spawn, and perhaps rivers being placed erratically since they use the same system as roads) I'd assume one of the mods in use is messing up with these functions, and could also be causing the event issues, since it relies somewhat on the planet. This last one is a wild guess more than anything else, still worth having it as a suspect.

As for more extra information on the case, the timer for events is exactly one hour **(if the server host has TemporalEventProtection set to true in the server config, if it's set to false, or the config isn't there, then there's no timer applied)**, so the variability you guys are getting of this is also something to take into account

**Comment by SfSec** [comment]
Hi Byte-Nova,

So I've collated the logs, and I've perused them too, but I want to note to you that when I press confirm on Send Event, there is nothing in the logs to indicate I've done that at any point in time. There is nothing thrown in the logs to read basically. And that could be a problem while trying to pinpoint this issue.

There is a part in the logs that indicates when RimTogether [RT] is saving for save and quit actions. 

I spoke to the Multiplayer host, and they've iterated and shown me that the Multiplayer xml file found in the attached zip is the list of all the mods available in the Optional folder.
They are not at all in required or other folders. They are all in the Optional folder.

Thanks for the information on the timer, that was really helpful. 

Can you please update the error thrown when a player is Sending an Event too fast after the first one to indicate they need to wait longer before sending another event? It will leave players less confused when this happens again.



[RimTogether SendEvent Issue_2.zip](https://github.com/user-attachments/files/16177130/RimTogether.SendEvent.Issue_2.zip)

I appreciate your assistance by the way. I hope all the logs help.

**Comment by Byte-Nova** [comment]
Closing since it's been diagnosed and fixed for the next release of the mod
