### ISSUE TITLE
v24.7.19.1 win virus detected

### ISSUE THREAD

**Issue by Eokai85** [RimworldTogether/Rimworld-Together#131]
Hi, the latest release is saying there is a virus detected in both windows versions
Trojan:Script/Sabsik.fl.A!ml

**Comment by Byte-Nova** [comment]
Thanks for waiting through the delay. **Some users have been reporting that this is an issue with Windows machines that aren't updated to the latest release, and are having the Microsoft Windows Defender marking the file as a false positive**. They also inform that updating the machine fixed the issue for them with no further problem.

I have been keeping tabs on the issue from time to time. From testing, **the antiviruses are specially keen on falsely marking the .exe file as malicious if it was compiled with the .NET Framework files inside**. Basically, they are the official library files from the .NET framework that we put inside so users can just boot the server without installing anything else (it's also the reason the .exe size is over 60MB instead of the 1MB it should be, convenience). There's also 1 of the antiviruses from VirusTotal that _sometimes_ marks it as malicious. Since that one is based on AI detection, I wouldn't give it much hope, specially if the rest don't trigger either.

**Here's a virus scan of the latest version, of the .exe file, WITH the .NET dependency inside:**
https://www.virustotal.com/gui/file/bb8f8d111fdf8ba7504d32f4a9288bc163314a528feef061d1aa20ab1d316dc8

**Here's a virus scan of the latest version, of the .exe file, WITHOUT the .NET dependency inside:**
https://www.virustotal.com/gui/file/8b4d29180ea6117101fb17e42d762f1e233a81f9a99a03ae6aed09142050ce2c

If you are having further inquiries with the issue please make sure to contact again. You also have access to the complete decompiled code of the mod if you want to take a throughout look at it, at this same repository.

**Comment by Eokai85** [comment]
Thank you, that puts my mind at ease :)
