### ISSUE TITLE
Totally Localizable Rimworld Together

### ISSUE THREAD

**Issue by SimobiSirOP** [RimworldTogether/Rimworld-Together#143]
Currently, our localization files supports only small fraction of files. (Description of Chat, Factions, Sites)

There is a need for  GoodWill, Faction Menu, Form Caravan, Aid, Event Sending, Global Market, Spying, Raids, Visiting, Transfers (Everything in WorldViewPatches.cs), MainButton, ChatTab, Join Server Menu (Login), Automatic Broadcasts (First time joining) 

Also, i see a untranslated "Send Caravan" button in planet menu, but can't find where it is in mod files, probably localization bug

(Sorry for my English)

**Comment by Byte-Nova** [comment]
Hello there, thanks for reaching out.

There's currently no complete localization for the mod, all we offer is a partial one. The mod is a work in progress that gets updated very quickly, and there's no way to add a complete localization (other than for English) that doesn't get instantly  outdated every update we launch because there's new content to be translated to every language in the localization.

Hopefully you understand the reasoning behind it.

**Comment by SimobiSirOP** [comment]
Thanks. 

I think you didn't understand what i mean.

I don't ask translation to every Language (Because i know, that it will require a team of translators). I mean about a way to translate some files using LanguageData (Defs), because right now mod has a lot of "HardCoded" text

**Comment by Alexandr199514** [comment]
If there is such a variant, I will be happy to translate it into Russian

**Comment by SimobiSirOP** [comment]
I think keyed way to access strings is our way to translation

**Comment by Byte-Nova** [comment]
Using keyeds should work, it just hasn't been implemented into the mod. Right now (almost) all the strings are hard-coded into the source, so they would have to be exported into keyed files for it to work. 

If someone is up for the task it would be appreciated, it's just not a priority in the mod development right now.

**Comment by Byte-Nova** [comment]
Closing issue because it's being worked on already at #145
