### ISSUE TITLE
Windows Defender Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by halberstam-vtg** [RimworldTogether/Rimworld-Together#199]
Status Quarantined
Quarnatined files are in a restricted area where they can't harm your device.  They will be removed automatically.

Details: This program is dangerous and executes commands from an attacker.

Affected items:

file: C:\users\username\desktop\GameServer.exe

**Comment by Byte-Nova** [comment]
Hey there, thanks for coming to share your worries regarding this. It isn't the first time this has happened so I'll be brief and try to explain it to my best competence.

Almost every release, looking all the way back to 1.2.0 or before that, we have been marked as false positives by some antiviruses, depending on the version including Windows Defender itself. **We have clues pointing out that the source of the false positive is to be related to us packing the ".NET" dependency inside the executable file** (the detections go away as soon as we don't pack said dependency automatically), so users don't need to download it separately to run the server (Similar to how Minecraft server owners require Java to boot it), **and in the case of Windows users, them *sometimes* not having the latest update of the OS**.

Since this is an open sourced project, if you are techy enough and want to rummage around the code, please feel free to do so since it's completely available on this repository so you can ensure nothing is wrong. There's also issue #131, that had the same problem if you are looking for more information regarding it.
